In [1]:
#https://www.shanelynn.ie/select-pandas-dataframe-rows-and-columns-using-iloc-loc-and-ix/

import pandas as pd
import random
import os
UK_PATH = "datasets/uk500"
csv_path = os.path.join(UK_PATH, 'uk-500.csv')

data = pd.read_csv(csv_path)

data['id'] = [random.randint(0, 1000) for x in range(data.shape[0])]

data.head(5)

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,373
1,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,508
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,650
3,Ulysses,Mcwalters,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,647
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,531

In [2]:
data.shape

(500, 12)

In [3]:
data.iloc[0]

first_name                                   Aleshia
last_name                                 Tomkiewicz
company_name                 Alan D Rosenburg Cpa Pc
address                                 14 Taylor St
city                               St. Stephens Ward
county                                          Kent
postal                                       CT2 7PP
phone1                                  01835-703597
phone2                                  01944-369967
email                        atomkiewicz@hotmail.com
web             http://www.alandrosenburgcpapc.co.uk
id                                               373
Name: 0, dtype: object

In [4]:
data.iloc[[0]] # first row of data frame

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,373

In [5]:
data.iloc[1] # 2nd row as series

first_name                                   Evan
last_name                               Zigomalas
company_name                   Cap Gemini America
address                               5 Binney St
city                                   Abbey Ward
county                            Buckinghamshire
postal                                   HP11 2AX
phone1                               01937-864715
phone2                               01714-737668
email                    evan.zigomalas@gmail.com
web             http://www.capgeminiamerica.co.uk
id                                            508
Name: 1, dtype: object

In [6]:
data.iloc[[1]] # 2nd row

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
1,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,508

In [7]:
data.iloc[[-1]] # last row

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
499,Mi,Richan,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk,356

In [8]:
data.iloc[:,0] # first column of dframe

0          Aleshia
1             Evan
2           France
3          Ulysses
4           Tyisha
5             Eric
6             Marg
7          Laquita
8             Lura
9           Yuette
10        Fernanda
11     Charlesetta
12        Corrinne
13          Niesha
14          Rueben
15         Michell
16           Edgar
17          Dewitt
18        Charisse
19             Mee
20           Peter
21         Octavio
22          Martha
23         Tamesha
24            Tess
25         Leonard
26        Svetlana
27             Pok
28       Augustine
29           Karma
          ...
470           Tony
471            Val
472            Mel
473       Isabella
474         Erasmo
475          Ivory
476         Nikita
477          Aleta
478           Owen
479        Pauline
480        Tijuana
481          Ahmad
482         Jamika
483        Derrick
484     Jacquelyne
485        Zachary
486         Sophia
487       Isabelle
488         Ronnie
489       Krystina
490         Rosita
491           Huey
492         Elbert
493           Pura
494         Alesia
495          Avery
496           Reid
497      Charlette
498      Celestina
499             Mi
Name: first_name, Length: 500, dtype: object

In [9]:
data.iloc[[:,0]]

SyntaxError: invalid syntax (<ipython-input-9-7954e7d9f4ac>, line 1)

In [10]:
data.iloc[:,1] # 2nd column

0      Tomkiewicz
1       Zigomalas
2         Andrade
3       Mcwalters
4          Veness
5           Rampy
6        Grasmick
7           Hisaw
8        Manzella
9          Klapec
10         Writer
11            Erm
12          Jaret
13          Bruch
14      Gastellum
15      Throssell
16          Kanne
17          Julio
18       Spinello
19       Lapinski
20      Gutierres
21      Salvadore
22        Teplica
23         Veigel
24          Sitra
25         Kufner
26         Tauras
27       Molaison
28       Growcock
29         Quarto
          ...
470    Diazdeleon
471        Villot
472      Picciuto
473    Piatkowski
474          Rhea
475       Lohrenz
476         Walka
477        Ligons
478       Jentzen
479         Fling
480      Machalek
481       Alsaqri
482        Conoly
483       Dolloff
484       Reibman
485    Freeburger
486       Gaucher
487          Kono
488       Brigman
489    Schlabaugh
490     Ausdemore
491       Stancil
492       Fiorino
493       Manciel
494         Katie
495          Veit
496       Euresti
497      Brenning
498         Keeny
499        Richan
Name: last_name, Length: 500, dtype: object

In [11]:
data.iloc[:,-1] # last column

0      373
1      508
2      650
3      647
4      531
5      273
6      970
7      627
8      699
9      252
10     296
11     199
12      64
13     446
14      82
15     619
16     663
17     281
18     562
19     164
20     898
21     819
22     153
23      95
24     778
25     247
26     550
27     101
28     971
29     139
      ...
470    147
471    342
472    886
473    419
474    422
475    805
476    623
477    558
478    657
479    693
480    705
481    846
482    848
483    311
484     11
485    794
486     10
487    625
488    291
489    454
490    234
491     81
492    634
493     38
494    809
495    393
496    405
497    201
498    345
499    356
Name: id, Length: 500, dtype: int64

In [12]:
# Multiple row and column selection using iloc and DataFrame
data.iloc[0:5] # 1st five rows of dataframe

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,373
1,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,508
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,650
3,Ulysses,Mcwalters,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,647
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,531

In [13]:
data.iloc[:,0:3] # first 3 columns of dataframe with all rows

      first_name   last_name                    company_name
0        Aleshia  Tomkiewicz         Alan D Rosenburg Cpa Pc
1           Evan   Zigomalas              Cap Gemini America
2         France     Andrade             Elliott, John W Esq
3        Ulysses   Mcwalters                  Mcmahan, Ben L
4         Tyisha      Veness                  Champagne Room
5           Eric       Rampy         Thompson, Michael C Esq
6           Marg    Grasmick   Wrangle Hill Auto Auct & Slvg
7        Laquita       Hisaw           In Communications Inc
8           Lura    Manzella                 Bizerba Usa Inc
9         Yuette      Klapec                       Max Video
10      Fernanda      Writer            K & R Associates Inc
11   Charlesetta         Erm                Cain, John M Esq
12      Corrinne       Jaret               Sound Vision Corp
13        Niesha       Bruch          Rowley/hansell Petetin
14        Rueben   Gastellum   Industrial Engineering Assocs
15       Michell   Throssell             Weiss Spirt & Guyer
16         Edgar       Kanne           Crowan, Kenneth W Esq
17        Dewitt       Julio            Rittenhouse Motor Co
18      Charisse    Spinello            Modern Plastics Corp
19           Mee    Lapinski        Galloway Electric Co Inc
20         Peter   Gutierres      Niagara Custombuilt Mfg Co
21       Octavio   Salvadore            Practical Periphrals
22        Martha     Teplica          Curtin, Patricia M Esq
23       Tamesha      Veigel             Wilhelm, James E Jr
24          Tess       Sitra                     Smart Signs
25       Leonard      Kufner    Arctic Star Distributing Inc
26      Svetlana      Tauras        Lensbower, Gregory L Esq
27           Pok    Molaison           Portal Metal Products
28     Augustine    Growcock               Lynema, Cliff Cpa
29         Karma      Quarto                 J C S Machinery
..           ...         ...                             ...
470         Tony  Diazdeleon              Dilling Harris Inc
471          Val      Villot            Horizon Air Magazine
472          Mel    Picciuto                  Avante Limited
473     Isabella  Piatkowski           Miller, William E Iii
474       Erasmo        Rhea                Martin Morrissey
475        Ivory     Lohrenz                 Auto Body Color
476       Nikita       Walka               Fred, Anthony Esq
477        Aleta      Ligons           Advantage Bookkeeping
478         Owen     Jentzen           Capital Fasteners Inc
479      Pauline       Fling      Cumberland Vacuum Products
480      Tijuana    Machalek          Schwartz, Thomas E Esq
481        Ahmad     Alsaqri    Alliance Construction Co Inc
482       Jamika      Conoly               Keller, Raymond C
483      Derrick     Dolloff         Proto Tek Manufacturing
484   Jacquelyne     Reibman            Great Clips For Hair
485      Zachary  Freeburger                 Country Kitchen
486       Sophia     Gaucher               T C E Systems Inc
487     Isabelle        Kono    Rock Springs Petroleum Equip
488       Ronnie     Brigman                  Howard Johnson
489     Krystina  Schlabaugh           Harris Oldsmobile Inc
490       Rosita   Ausdemore               Jurdem, Scott Esq
491         Huey     Stancil                   Lindner Funds
492       Elbert     Fiorino            Donald, G Nelson Esq
493         Pura     Manciel                  Cia Inspection
494       Alesia       Katie    Nelsons Trmt & Pest Cntrl Co
495        Avery        Veit      Plaza Gourmet Delicatessen
496         Reid     Euresti            Fitzgerald, Edward J
497    Charlette    Brenning              Furey & Associates
498    Celestina       Keeny        Bfg Federal Credit Union
499           Mi      Richan  Nelson Wright Haworth Golf Crs

[500 rows x 3 columns]

In [14]:
data.iloc[[47, 53, 59, 61], [1, 2, 3, 5, 7]]#row 48th, 54rd, 60th 62st columns 2nd 3rd 4th 6th 8th

,last_name,company_name,address,county,phone1
47,Devereux,Cash 4 Checks,3 North View #35,West Yorkshire,01607-269930
53,Klingaman,Welders Supply,67 Micawber St,Greater London,01712-135466
59,Chisum,Bohs Well Drilling Inc,662 Grove Park,Nottinghamshire,01835-634521
61,Bairo,"Reid, Carleton B Esq",3 August Rd,Surrey,01670-813697

In [15]:
data.iloc[0:5, 5:8]

            county    postal        phone1
0             Kent   CT2 7PP  01835-703597
1  Buckinghamshire  HP11 2AX  01937-864715
2      Bournemouth   BH6 3BE  01347-368222
3     Lincolnshire  DN36 5RP  01912-771311
4    West Midlands   B70 9DT  01547-429341

In [16]:
print(type(data.iloc[0])) #series

<class 'pandas.core.series.Series'>

In [17]:
print(type(data.iloc[[0]])) #dataFrame

<class 'pandas.core.frame.DataFrame'>

In [18]:
print(type(data.iloc[0:1])) #dataFrame

<class 'pandas.core.frame.DataFrame'>

In [19]:
print(type(data.iloc[0:2])) #dataFrame

<class 'pandas.core.frame.DataFrame'>

In [20]:
data.set_index("last_name", inplace=False)

,first_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
last_name,,,,,,,,,,,
Tomkiewicz,Aleshia,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,373
Zigomalas,Evan,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,508
Andrade,France,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,650
Mcwalters,Ulysses,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,647
Veness,Tyisha,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,531
Rampy,Eric,"Thompson, Michael C Esq",9472 Lind St,Desborough,Northamptonshire,NN14 2GH,01969-886290,01545-817375,erampy@rampy.co.uk,http://www.thompsonmichaelcesq.co.uk,273
Grasmick,Marg,Wrangle Hill Auto Auct & Slvg,7457 Cowl St #70,Bargate Ward,Southampton,SO14 3TY,01865-582516,01362-620532,marg@hotmail.com,http://www.wranglehillautoauctslvg.co.uk,970
Hisaw,Laquita,In Communications Inc,20 Gloucester Pl #96,Chirton Ward,Tyne & Wear,NE29 7AD,01746-394243,01590-982428,laquita@yahoo.com,http://www.incommunicationsinc.co.uk,627
Manzella,Lura,Bizerba Usa Inc,929 Augustine St,Staple Hill Ward,South Gloucestershire,BS16 4LL,01907-538509,01340-713951,lura@hotmail.com,http://www.bizerbausainc.co.uk,699
Klapec,Yuette,Max Video,45 Bradfield St #166,Parwich,Derbyshire,DE6 1QN,01903-649460,01933-512513,yuette.klapec@klapec.co.uk,http://www.maxvideo.co.uk,252
Writer,Fernanda,K & R Associates Inc,620 Northampton St,Wilmington,Kent,DA2 7PP,01630-202053,01687-879391,fernanda@writer.co.uk,http://www.krassociatesinc.co.uk,296
Erm,Charlesetta,"Cain, John M Esq",5 Hygeia St,Loundsley Green Ward,Derbyshire,S40 4LY,01276-816806,01517-624517,charlesetta_erm@gmail.com,http://www.cainjohnmesq.co.uk,199
Jaret,Corrinne,Sound Vision Corp,2150 Morley St,Dee Ward,Dumfries and Galloway,DG8 7DE,01625-932209,01642-322954,corrinne_jaret@gmail.com,http://www.soundvisioncorp.co.uk,64
Bruch,Niesha,Rowley/hansell Petetin,24 Bolton St,"Broxburn, Uphall and Winchburg",West Lothian,EH52 5TL,01874-856950,01342-793603,niesha.bruch@yahoo.com,http://www.rowleyhansellpetetin.co.uk,446
Gastellum,Rueben,Industrial Engineering Assocs,4 Forrest St,Weston-Super-Mare,North Somerset,BS23 3HG,01976-755279,01956-535511,rueben_gastellum@gastellum.co.uk,http://www.industrialengineeringassocs.co.uk,82
Throssell,Michell,Weiss Spirt & Guyer,89 Noon St,Carbrooke,Norfolk,IP25 6JQ,01967-580851,01672-496478,mthrossell@throssell.co.uk,http://www.weissspirtguyer.co.uk,619
Kanne,Edgar,"Crowan, Kenneth W Esq",99 Guthrie St,New Milton,Hampshire,BH25 5DF,01326-532337,01666-638176,edgar.kanne@yahoo.com,http://www.crowankennethwesq.co.uk,663
Julio,Dewitt,Rittenhouse Motor Co,7 Richmond St,Parkham,Devon,EX39 5DJ,01253-528327,01241-964675,dewitt.julio@hotmail.com,http://www.rittenhousemotorco.co.uk,281
Spinello,Charisse,Modern Plastics Corp,9165 Primrose St,Darnall Ward,"Yorkshire, South",S4 7WN,01719-831436,01207-428520,charisse_spinello@spinello.co.uk,http://www.modernplasticscorp.co.uk,562
Lapinski,Mee,Galloway Electric Co Inc,9 Pengwern St,Marldon,Devon,TQ3 1SA,01578-287816,01939-815208,mee.lapinski@yahoo.com,http://www.gallowayelectriccoinc.co.uk,164
Gutierres,Peter,Niagara Custombuilt Mfg Co,4410 Tarlton St,Prestatyn Community,Denbighshire,LL19 9EG,01842-767201,01859-648598,peter_gutierres@yahoo.com,http://www.niagaracustombuiltmfgco.co.uk,898
Salvadore,Octavio,Practical Periphrals,6949 Bourne St,Lye and Stourbridge North Ward,West Midlands,DY5 2QP,01552-709248,01743-139456,octavio.salvadore@yahoo.com,http://www.practicalperiphrals.co.uk,819
Teplica,Martha,"Curtin, Patricia M Esq",148 Rembrandt St,Warlingham,Surrey,CR6 9SW,01677-684257,01583-287367,mteplica@teplica.co.uk,http://www.curtinpatriciamesq.co.uk,153
Veigel,Tamesha,"Wilhelm, James E Jr",2200 Nelson St #58,Newport,Isle of Wight,PO30 5AL,01217-342071,01280-786847,tveigel@veigel.co.uk,http://www.wilhelmjamesejr.co.uk,95
Sitra,Tess,Smart Signs,61 Rossett St,Chichester,West Sussex,PO19 1RH,01473-229124,01848-116775,tess_sitra@hotmail.com,http://www.smartsigns.co.uk,778
Kufner,Leonard,Arctic Star Distributing Inc,41 Canning St,Steornabhagh a Deas Ward,Western Isles,HS1 2PZ,01230-623547,01604-718601,lkufner@kufner.co.uk,http://www.arcticstardistributinginc.co.uk,247
Tauras,Svetlana,"Lensbower, Gregory L Esq",8289 Cadogan St,South Ward,North Eart Lincolnshire,DN33 1AU,01781-827317,01509-121140,svetlana_tauras@tauras.co.uk,http://www.lensbowergregorylesq.co.uk,550
Molaison,Pok,Portal Metal Products,211 Hobart St,Newquay,Cornwall,TR7 1LS,01866-248660,01315-284286,pok@yahoo.com,http://www.portalmetalproducts.co.uk,101
Growcock,Augustine,"Lynema, Cliff Cpa",114 Falkland St #8845,Brimpton,Berkshire,RG7 4RF,01541-802635,01926-108010,augustine.growcock@growcock.co.uk,http://www.lynemacliffcpa.co.uk,971
Quarto,Karma,J C S Machinery,1 Birkett St,Shard End Ward,West Midlands,B33 0NH,01857-864722,01307-667811,kquarto@gmail.com,http://www.jcsmachinery.co.uk,139
...,...,...,...,...,...,...,...,...,...,...,...
Diazdeleon,Tony,Dilling Harris Inc,529 Llanrwst St,Southam,Gloucestershire,GL52 8TW,01765-102036,01877-593275,tony@gmail.com,http://www.dillingharrisinc.co.uk,147
Villot,Val,Horizon Air Magazine,1980 Tynemouth St,Almond Ward,West Lothian,EH52 5PY,01375-870188,01602-987840,val@yahoo.com,http://www.horizonairmagazine.co.uk,342
Picciuto,Mel,Avante Limited,8598 Rumney Rd,Hylands Ward,Essex,RM11 1QL,01885-270480,01268-443299,mel.picciuto@gmail.com,http://www.avantelimited.co.uk,886
Piatkowski,Isabella,"Miller, William E Iii",9283 Ruth St #81,Dormers Wells Ward,Greater London,UB1 2FH,01979-186995,01998-980054,isabella_piatkowski@piatkowski.co.uk,http://www.millerwilliameiii.co.uk,419
Rhea,Erasmo,Martin Morrissey,5544 Sutherland St,Mortehoe,Devon,EX34 7DQ,01507-386397,01899-316385,erasmo_rhea@hotmail.com,http://www.martinmorrissey.co.uk,422
Lohrenz,Ivory,Auto Body Color,9 Jackson St,Parr Ward,Merseyside,WA9 3QW,01876-642683,01651-132519,ivory@hotmail.com,http://www.autobodycolor.co.uk,805
Walka,Nikita,"Fred, Anthony Esq",3612 Bixteth St,Hucknall North Ward,Nottinghamshire,NG15 8DD,01282-123434,01724-455145,nwalka@hotmail.com,http://www.fredanthonyesq.co.uk,623
Ligons,Aleta,Advantage Bookkeeping,4545 Victoria Rd,Kilbirnie and Beith Ward,North Ayrshire,KA15 1AT,01952-535977,01715-637895,aleta_ligons@hotmail.com,http://www.advantagebookkeeping.co.uk,558
Jentzen,Owen,Capital Fasteners Inc,5 Hampden St,Liscard Ward,Merseyside,CH45 4RN,01467-142439,01917-137038,owen_jentzen@jentzen.co.uk,http://www.capitalfastenersinc.co.uk,657
Fling,Pauline,Cumberland Vacuum Products,6452 Pilgrim St #5,Seven Sisters Ward,Greater London,N15 6TH,01990-476494,01458-113457,pfling@fling.co.uk,http://www.cumberlandvacuumproducts.co.uk,693
Machalek,Tijuana,"Schwartz, Thomas E Esq",1149 Highfield Rd #996,Fareham South Ward,Hampshire,PO14 9JJ,01242-532395,01336-686264,tijuana.machalek@gmail.com,http://www.schwartzthomaseesq.co.uk,705
Alsaqri,Ahmad,Alliance Construction Co Inc,21 Pickwick St,Sutton cum Duckmanton,Derbyshire,S44 5DS,01567-555570,01852-550588,ahmad.alsaqri@yahoo.com,http://www.allianceconstructioncoinc.co.uk,846
Conoly,Jamika,"Keller, Raymond C",19 Soho St,Whitley Ward,Berkshire,RG1 9XH,01726-595316,01597-168997,jamika_conoly@conoly.co.uk,http://www.kellerraymondc.co.uk,848
Dolloff,Derrick,Proto Tek Manufacturing,236 Blantyre Rd,Everton Ward,Merseyside,L6 2EN,01982-734773,01619-554437,derrick_dolloff@gmail.com,http://www.prototekmanufacturing.co.uk,311
Reibman,Jacquelyne,Great Clips For Hair,70 Lilly Rd,Shirley Ward,Greater London,CR0 7PT,01846-581451,01850-754504,jacquelyne_reibman@yahoo.com,http://www.greatclipsforhair.co.uk,11
Freeburger,Zachary,Country Kitchen,58 Gloucester Rd,Holbrook,Derbyshire,DE56 0TX,01888-641397,01240-433924,zachary.freeburger@freeburger.co.uk,http://www.countrykitchen.co.uk,794
Gaucher,Sophia,T C E Systems Inc,88 Upper Harrington St,North East Ward,North Lanarkshire,G69 8EL,01504-539114,01254-919378,sophia.gaucher@hotmail.com,http://www.tcesystemsinc.co.uk,10
Kono,Isabelle,Rock Springs Petroleum Equip,4920 Fazakerley Rd,Plymstock Dunstone Ward,Devon,PL9 8RD,01552-682601,01953-816728,isabelle.kono@yahoo.com,http://www.rockspringspetroleumequip.co.uk,625
Brigman,Ronnie,Howard Johnson,6 Morley St,Batchwood Ward,Hertfordshire,AL3 5JN,01943-754681,01972-686199,ronnie@brigman.co.uk,http://www.howardjohnson.co.uk,291
Schlabaugh,Krystina,Harris Oldsmobile Inc,7316 Friar St,Salvington Ward,West Sussex,BN13 3FL,01441-846477,01332-799979,kschlabaugh@schlabaugh.co.uk,http://www.harrisoldsmobileinc.co.uk,454
Ausdemore,Rosita,"Jurdem, Scott Esq",8 Heathfield St #657,Hailsham,East Sussex,BN27 1AJ,01273-236188,01997-765432,rausdemore@hotmail.com,http://www.jurdemscottesq.co.uk,234
Stancil,Huey,Lindner Funds,275 Peel Sq,Park Ward,North Eart Lincolnshire,DN32 0PT,01502-139578,01468-195646,hstancil@hotmail.com,http://www.lindnerfunds.co.uk,81
Fiorino,Elbert,"Donald, G Nelson Esq",726 Westmoreland Place,Ballochmyle Ward,East Ayrshire,KA5 6EL,01724-467889,01992-537553,elbert@hotmail.com,http://www.donaldgnelsonesq.co.uk,634
Manciel,Pura,Cia Inspection,7 Water St,Priory Heath Ward,Suffolk,IP3 9RB,01853-412588,01386-437186,pura.manciel@yahoo.com,http://www.ciainspection.co.uk,38
Katie,Alesia,Nelsons Trmt & Pest Cntrl Co,4 Covent Garden,Farnworth Ward,Greater Manchester,BL4 7AF,01333-436799,01240-614527,alesia_katie@gmail.com,http://www.nelsonstrmtpestcntrlco.co.uk,809
Veit,Avery,Plaza Gourmet Delicatessen,9166 Devon St #905,Knightsbridge and Belgravia Wa,Greater London,SW1W 8JY,01748-625058,01369-185737,avery@veit.co.uk,http://www.plazagourmetdelicatessen.co.uk,393
Euresti,Reid,"Fitzgerald, Edward J",70 Foster St,Inverness Ness-Side Ward,Highland,IV2 6WT,01916-963261,01370-319414,reuresti@euresti.co.uk,http://www.fitzgeraldedwardj.co.uk,405
Brenning,Charlette,Furey & Associates,714 Fonthill Rd,Darton West Ward,South Yorkshire,S75 5EJ,01888-152110,01301-312487,cbrenning@brenning.co.uk,http://www.fureyassociates.co.uk,201
Keeny,Celestina,Bfg Federal Credit Union,9 Milton St,Consett North ED,County Durham,DH8 5LP,01877-379681,01600-463475,celestina_keeny@gmail.com,http://www.bfgfederalcreditunion.co.uk,345
Richan,Mi,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk,356

In [21]:
data.head()

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,373
1,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,508
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,650
3,Ulysses,Mcwalters,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,647
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,531

In [22]:
#The Pandas loc indexer can be used with DataFrames for two different use cases:

# a.) Selecting rows by label/index
# b.) Selecting rows with a boolean / conditional lookup

data.set_index("last_name", inplace=True)

In [23]:
data.head()

,first_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
last_name,,,,,,,,,,,
Tomkiewicz,Aleshia,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,373
Zigomalas,Evan,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,508
Andrade,France,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,650
Mcwalters,Ulysses,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,647
Veness,Tyisha,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,531

In [24]:
data.head()

,first_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
last_name,,,,,,,,,,,
Tomkiewicz,Aleshia,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,373
Zigomalas,Evan,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,508
Andrade,France,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,650
Mcwalters,Ulysses,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,647
Veness,Tyisha,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,531

In [25]:
data.loc['Andrade']

first_name                                France
company_name                 Elliott, John W Esq
address                             8 Moor Place
city              East Southbourne and Tuckton W
county                               Bournemouth
postal                                   BH6 3BE
phone1                              01347-368222
phone2                              01935-821636
email                 france.andrade@hotmail.com
web             http://www.elliottjohnwesq.co.uk
id                                           650
Name: Andrade, dtype: object

In [26]:
data.loc[['Andrade']]

,first_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
last_name,,,,,,,,,,,
Andrade,France,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,650

In [27]:
data.loc['Andrade': 'Veness']

,first_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
last_name,,,,,,,,,,,
Andrade,France,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,650
Mcwalters,Ulysses,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,647
Veness,Tyisha,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,531

In [28]:
data.loc[['Andrade', 'Veness'], ['first_name','address', 'city']]

          first_name            address                            city
last_name
Andrade       France       8 Moor Place  East Southbourne and Tuckton W
Veness        Tyisha  5396 Forth Street      Greets Green and Lyng Ward

In [29]:
data.loc['Andrade': 'Veness', ['first_name','address', 'city']]

          first_name            address                            city
last_name
Andrade       France       8 Moor Place  East Southbourne and Tuckton W
Mcwalters    Ulysses      505 Exeter Rd              Hawerby cum Beesby
Veness        Tyisha  5396 Forth Street      Greets Green and Lyng Ward

In [30]:
data.loc['Andrade': 'Veness', 'city': 'email']

,city,county,postal,phone1,phone2,email
last_name,,,,,,
Andrade,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com
Mcwalters,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com
Veness,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com

In [31]:
#  Change the index to be based on the 'id' column
data.set_index('id', inplace=True)

In [32]:
data.loc[477]

,first_name,company_name,address,city,county,postal,phone1,phone2,email,web
id,,,,,,,,,,
477,Cheryll,Blaineco Structural Movers,666 Moor Place,Shepway South Ward,Kent,ME15 8ST,01780-380120,01494-202350,cheryll_yurich@yurich.co.uk,http://www.blainecostructuralmovers.co.uk
477,Aleisha,Pathe Cmptr Cntrl Systems Corp,341 Birchfield St,Wareham St. Martin,Dorset,BH16 6JJ,01341-997268,01864-899304,aleisha.lemm@gmail.com,http://www.pathecmptrcntrlsystemscorp.co.uk

In [33]:
# Boolean / Logical index using loc
data.loc[data['first_name'] == 'Antonio']

,first_name,company_name,address,city,county,postal,phone1,phone2,email,web
id,,,,,,,,,,
16,Antonio,Combs Sheetmetal,353 Standish St #8264,Little Parndon and Hare Street,Hertfordshire,CM20 2HT,01559-403415,01388-777812,antonio.villamarin@gmail.com,http://www.combssheetmetal.co.uk
903,Antonio,Saint Thomas Creations,425 Howley St,Gaer Community,Newport,NP20 3DE,01463-409090,01242-318420,antonio_glasford@glasford.co.uk,http://www.saintthomascreations.co.uk
158,Antonio,Radisson Suite Hotel,35 Elton St #3,Ipplepen,Devon,TQ12 5LL,01324-171614,01442-946357,antonio.heilig@gmail.com,http://www.radissonsuitehotel.co.uk

In [34]:
data.loc[data['first_name'] == 'Erasmo', ['company_name', 'email', 'phone1']]

           company_name                         email        phone1
id
647  Active Air Systems  erasmo.talentino@hotmail.com  01492-454455
816            Pan Optx             egath@hotmail.com  01445-796544
422    Martin Morrissey       erasmo_rhea@hotmail.com  01507-386397